export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const GET_SPECIFIC_PROJECT = 'GET_SPECIFIC_PROJECT';

export const GET_REMARKS = 'GET_REMARKS';
export const ADD_REMARK = 'ADD_REMARK';
export const DELETE_REMARK = 'DELETE_REMARK';
export const REMARKS_LOADING = 'REMARKS_LOADING';
export const GET_SPECIFIC_REMARK = 'GET_SPECIFIC_REMARK';


export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';